version: "2.4"
services:
  vehicle:
    build: .
    network_mode: host
    privileged: true
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /root/.Xauthority:/root/.Xauthority
      - ${PWD}/vehicle_track_source:/vehicle/track
      - ${PWD}/yolo_weights_params:/vehicle/yolo_weights_params
